name: latihan_flutter_intermediate
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  lottie:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 3.0.2
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/lottie/hello.json
  uses-material-design: true
